# Generated by Django 4.2 on 2023-04-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermessage_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserMessage', to='users.profile'),
        ),
    ]
